### ISSUE TITLE
Unable to complete "cta2020-setup-user"

### ISSUE THREAD

**Issue by frederickz** [Computational-Content-Analysis-2020/frequently-asked-questions-spring#15]
Hi I was wondering how to solve this when I run `cta2020-setup-user`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/proccessing.py", line 10, in <module>
    nlp = spacy.load("en")
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cta2020-setup-user", line 5, in <module>
    from lucem_illud_2020._backend import makeUser
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/__init__.py", line 15, in <module>
    from .loaders import *
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/loaders.py", line 16, in <module>
    from .proccessing import normalizeTokens, trainTestSplit, word_tokenize, sent_tokenize
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/proccessing.py", line 12, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by timhannifan** [comment]
Run `python -m spacy download en`. See [TA's comment on Canvas.](https://canvas.uchicago.edu/courses/28544/discussion_topics/249422)

**Comment by bhargavvader** [comment]
Thanks for pointing this out @timhannifan ! I've also opened a new issue with this error so it is easier to find.

**Comment by frederickz** [comment]
Thank you! Sorry for missing the announcements.
