### ISSUE TITLE
Unable to complete "cta2020-setup-user" step

### ISSUE THREAD

**Issue by DSharm** [Computational-Content-Analysis-2020/frequently-asked-questions-spring#5]
Hi - I was able to install the class package, but neither of the set up commands worked for me. This is the error message I get - is anyone else experiencing the same?

![Screen Shot 2020-04-07 at 12 49 48 PM](https://user-images.githubusercontent.com/15899459/78702742-aed4d000-78ce-11ea-8448-2a7869fc1891.png)

**Comment by DSharm** [comment]
In particular, I think there's an issue with the 
`try: nlp = spacy.load('en')
except OSError: nlp = spacy.load('en_core_web_sm')`

code in processing.py. I seem to be able to import spacy but can't load 'en' or 'en_core_web_sm'.

**Comment by bhargavvader** [comment]
Hello Damini, could you run ```python -m spacy download en``` in terminal and then run the command again? You can find similar troubleshooting for this: [here](https://github.com/Computational-Content-Analysis-2020/frequently-asked-questions/issues/9).

**Comment by DSharm** [comment]
Thanks! That seems to have worked. Now I'm at the "Pushing to GitHub" stage of the setup, and have been for about 30 minutes. Is that to be expected?

**Comment by DSharm** [comment]
I killed the process using Ctrl + Z and manually did a "git push" which seems to have worked

**Comment by frederickz** [comment]
I also have the same question, but a different circumstance.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/proccessing.py", line 10, in <module>
    nlp = spacy.load("en")
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cta2020-setup-user", line 5, in <module>
    from lucem_illud_2020._backend import makeUser
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/__init__.py", line 15, in <module>
    from .loaders import *
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/loaders.py", line 16, in <module>
    from .proccessing import normalizeTokens, trainTestSplit, word_tokenize, sent_tokenize
  File "/usr/local/lib/python3.7/site-packages/lucem_illud_2020/proccessing.py", line 12, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
